import { Deal } from '@/types/deal';

export interface RegionInfo {
  name: string;
  coords: [number, number];
  abbr: string;
}

export interface LocationData {
  region: string;
  count: number;
  deals: Deal[];
  cities: string[];
  regionInfo: RegionInfo | null;
}

export const US_REGIONS: Record<string, RegionInfo> = {
  'California': { name: 'California', coords: [36.7783, -119.4179], abbr: 'CA' },
  'New York': { name: 'New York', coords: [40.7128, -74.0060], abbr: 'NY' },
  'Texas': { name: 'Texas', coords: [31.9686, -99.9018], abbr: 'TX' },
  'Florida': { name: 'Florida', coords: [27.7663, -82.6404], abbr: 'FL' },
  'Illinois': { name: 'Illinois', coords: [40.3363, -89.0022], abbr: 'IL' },
  'Washington': { name: 'Washington', coords: [47.7511, -120.7401], abbr: 'WA' },
  'Massachusetts': { name: 'Massachusetts', coords: [42.2352, -71.0275], abbr: 'MA' },
  'Colorado': { name: 'Colorado', coords: [39.0598, -105.3111], abbr: 'CO' },
  'Georgia': { name: 'Georgia', coords: [33.0406, -83.6431], abbr: 'GA' },
  'North Carolina': { name: 'North Carolina', coords: [35.5397, -79.8431], abbr: 'NC' },
  'Nevada': { name: 'Nevada', coords: [38.8026, -116.4194], abbr: 'NV' },
  'Oregon': { name: 'Oregon', coords: [43.8041, -120.5542], abbr: 'OR' },
  'Arizona': { name: 'Arizona', coords: [34.0489, -111.0937], abbr: 'AZ' },
  'Utah': { name: 'Utah', coords: [39.3210, -111.0937], abbr: 'UT' },
  'Pennsylvania': { name: 'Pennsylvania', coords: [41.2033, -77.1945], abbr: 'PA' },
  'Ohio': { name: 'Ohio', coords: [40.4173, -82.9071], abbr: 'OH' },
  'Michigan': { name: 'Michigan', coords: [44.3148, -85.6024], abbr: 'MI' },
  'Virginia': { name: 'Virginia', coords: [37.4316, -78.6569], abbr: 'VA' },
  'Maryland': { name: 'Maryland', coords: [39.0458, -76.6413], abbr: 'MD' },
  'Minnesota': { name: 'Minnesota', coords: [46.7296, -94.6859], abbr: 'MN' },
  'Tennessee': { name: 'Tennessee', coords: [35.5175, -86.5804], abbr: 'TN' },
  'Connecticut': { name: 'Connecticut', coords: [41.6032, -73.0877], abbr: 'CT' },
  'New Jersey': { name: 'New Jersey', coords: [40.0583, -74.4057], abbr: 'NJ' },
  'Wisconsin': { name: 'Wisconsin', coords: [43.7844, -88.7879], abbr: 'WI' },
  'Indiana': { name: 'Indiana', coords: [40.2732, -86.1349], abbr: 'IN' },
  'Missouri': { name: 'Missouri', coords: [37.9643, -91.8318], abbr: 'MO' },
  'Alabama': { name: 'Alabama', coords: [32.3617, -86.2792], abbr: 'AL' },
  'South Carolina': { name: 'South Carolina', coords: [33.8361, -81.1637], abbr: 'SC' },
  'Louisiana': { name: 'Louisiana', coords: [31.2449, -92.1450], abbr: 'LA' },
  'Kentucky': { name: 'Kentucky', coords: [37.8393, -84.2700], abbr: 'KY' },
  'Oklahoma': { name: 'Oklahoma', coords: [35.5889, -97.5348], abbr: 'OK' },
};

// Add international countries
export const INTERNATIONAL_REGIONS: Record<string, RegionInfo> = {
  'Canada': { name: 'Canada', coords: [56.1304, -106.3468], abbr: 'CA' },
  'United Kingdom': { name: 'United Kingdom', coords: [55.3781, -3.4360], abbr: 'UK' },
  'Italy': { name: 'Italy', coords: [41.8719, 12.5674], abbr: 'IT' },
  'Germany': { name: 'Germany', coords: [51.1657, 10.4515], abbr: 'DE' },
  'France': { name: 'France', coords: [46.2276, 2.2137], abbr: 'FR' },
  'Spain': { name: 'Spain', coords: [40.4637, -3.7492], abbr: 'ES' },
  'Netherlands': { name: 'Netherlands', coords: [52.1326, 5.2913], abbr: 'NL' },
  'Switzerland': { name: 'Switzerland', coords: [46.8182, 8.2275], abbr: 'CH' },
  'Sweden': { name: 'Sweden', coords: [60.1282, 18.6435], abbr: 'SE' },
  'Norway': { name: 'Norway', coords: [60.4720, 8.4689], abbr: 'NO' },
  'Denmark': { name: 'Denmark', coords: [56.2639, 9.5018], abbr: 'DK' },
  'Finland': { name: 'Finland', coords: [61.9241, 25.7482], abbr: 'FI' },
  'Australia': { name: 'Australia', coords: [-25.2744, 133.7751], abbr: 'AU' },
  'Japan': { name: 'Japan', coords: [36.2048, 138.2529], abbr: 'JP' },
  'South Korea': { name: 'South Korea', coords: [35.9078, 127.7669], abbr: 'KR' },
  'China': { name: 'China', coords: [35.8617, 104.1954], abbr: 'CN' },
  'India': { name: 'India', coords: [20.5937, 78.9629], abbr: 'IN' },
  'Brazil': { name: 'Brazil', coords: [-14.2350, -51.9253], abbr: 'BR' },
  'Mexico': { name: 'Mexico', coords: [23.6345, -102.5528], abbr: 'MX' },
  'Israel': { name: 'Israel', coords: [31.0461, 34.8516], abbr: 'IL' },
  'Singapore': { name: 'Singapore', coords: [1.3521, 103.8198], abbr: 'SG' },
  'Hong Kong': { name: 'Hong Kong', coords: [22.3193, 114.1694], abbr: 'HK' },
  'South Africa': { name: 'South Africa', coords: [-30.5595, 22.9375], abbr: 'ZA' },
  'Nigeria': { name: 'Nigeria', coords: [9.0820, 8.6753], abbr: 'NG' },
  'Kenya': { name: 'Kenya', coords: [-0.0236, 37.9062], abbr: 'KE' },
  'UAE': { name: 'UAE', coords: [23.4241, 53.8478], abbr: 'AE' },
  'Russia': { name: 'Russia', coords: [61.5240, 105.3188], abbr: 'RU' },
  'Poland': { name: 'Poland', coords: [51.9194, 19.1451], abbr: 'PL' },
  'Czech Republic': { name: 'Czech Republic', coords: [49.8175, 15.4730], abbr: 'CZ' },
  'Austria': { name: 'Austria', coords: [47.5162, 14.5501], abbr: 'AT' },
  'Belgium': { name: 'Belgium', coords: [50.5039, 4.4699], abbr: 'BE' },
  'Portugal': { name: 'Portugal', coords: [39.3999, -8.2245], abbr: 'PT' },
  'Ireland': { name: 'Ireland', coords: [53.1424, -7.6921], abbr: 'IE' },
  'New Zealand': { name: 'New Zealand', coords: [-40.9006, 174.8860], abbr: 'NZ' },
  'Argentina': { name: 'Argentina', coords: [-38.4161, -63.6167], abbr: 'AR' },
  'Chile': { name: 'Chile', coords: [-35.6751, -71.5430], abbr: 'CL' },
  'Colombia': { name: 'Colombia', coords: [4.5709, -74.2973], abbr: 'CO' },
  'Peru': { name: 'Peru', coords: [-9.1900, -75.0152], abbr: 'PE' },
  'Thailand': { name: 'Thailand', coords: [15.8700, 100.9925], abbr: 'TH' },
  'Vietnam': { name: 'Vietnam', coords: [14.0583, 108.2772], abbr: 'VN' },
  'Indonesia': { name: 'Indonesia', coords: [-0.7893, 113.9213], abbr: 'ID' },
  'Malaysia': { name: 'Malaysia', coords: [4.2105, 101.9758], abbr: 'MY' },
  'Philippines': { name: 'Philippines', coords: [12.8797, 121.7740], abbr: 'PH' },
  'Turkey': { name: 'Turkey', coords: [38.9637, 35.2433], abbr: 'TR' },
  'Egypt': { name: 'Egypt', coords: [26.0975, 31.2357], abbr: 'EG' },
  'Morocco': { name: 'Morocco', coords: [31.7917, -7.0926], abbr: 'MA' },
};

// Combine all regions
export const ALL_REGIONS = { ...US_REGIONS, ...INTERNATIONAL_REGIONS };

export const CITY_TO_REGION: Record<string, string> = {
  // California cities
  'San Francisco': 'California',
  'Los Angeles': 'California',
  'San Diego': 'California',
  'Sacramento': 'California',
  'San Jose': 'California',
  'Oakland': 'California',
  'Fremont': 'California',
  'Santa Clara': 'California',
  'Palo Alto': 'California',
  'Mountain View': 'California',
  'Cupertino': 'California',
  'Sunnyvale': 'California',
  'Santa Monica': 'California',
  'Long Beach': 'California',
  'Irvine': 'California',
  'Anaheim': 'California',
  'Berkeley': 'California',
  'Pasadena': 'California',
  'Redwood City': 'California',
  'Menlo Park': 'California',
  
  // New York cities
  'New York': 'New York',
  'Brooklyn': 'New York',
  'Manhattan': 'New York',
  'Queens': 'New York',
  'Bronx': 'New York',
  'Staten Island': 'New York',
  'Buffalo': 'New York',
  'Rochester': 'New York',
  'Syracuse': 'New York',
  'Albany': 'New York',
  
  // Texas cities
  'Austin': 'Texas',
  'Houston': 'Texas',
  'Dallas': 'Texas',
  'San Antonio': 'Texas',
  'Fort Worth': 'Texas',
  'El Paso': 'Texas',
  'Arlington': 'Texas',
  'Corpus Christi': 'Texas',
  'Plano': 'Texas',
  'Lubbock': 'Texas',
  
  // Florida cities
  'Miami': 'Florida',
  'Orlando': 'Florida',
  'Tampa': 'Florida',
  'Jacksonville': 'Florida',
  'Fort Lauderdale': 'Florida',
  'St. Petersburg': 'Florida',
  'Tallahassee': 'Florida',
  'Gainesville': 'Florida',
  'Clearwater': 'Florida',
  'West Palm Beach': 'Florida',
  
  // Illinois cities
  'Chicago': 'Illinois',
  'Aurora': 'Illinois',
  'Rockford': 'Illinois',
  'Joliet': 'Illinois',
  'Naperville': 'Illinois',
  'Springfield': 'Illinois',
  'Peoria': 'Illinois',
  'Elgin': 'Illinois',
  
  // Washington cities
  'Seattle': 'Washington',
  'Spokane': 'Washington',
  'Tacoma': 'Washington',
  'Vancouver': 'Washington',
  'Bellevue': 'Washington',
  'Everett': 'Washington',
  'Kent': 'Washington',
  'Renton': 'Washington',
  'Redmond': 'Washington',
  
  // Massachusetts cities
  'Boston': 'Massachusetts',
  'Worcester': 'Massachusetts',
  'Lowell': 'Massachusetts',
  'Cambridge': 'Massachusetts',
  'New Bedford': 'Massachusetts',
  'Brockton': 'Massachusetts',
  'Quincy': 'Massachusetts',
  
  // Colorado cities
  'Denver': 'Colorado',
  'Colorado Springs': 'Colorado',
  'Fort Collins': 'Colorado',
  'Lakewood': 'Colorado',
  'Thornton': 'Colorado',
  'Arvada': 'Colorado',
  'Boulder': 'Colorado',
  
  // Georgia cities
  'Atlanta': 'Georgia',
  'Augusta': 'Georgia',
  'Savannah': 'Georgia',
  'Athens': 'Georgia',
  'Sandy Springs': 'Georgia',
  'Roswell': 'Georgia',
  'Macon': 'Georgia',
  
  // North Carolina cities
  'Raleigh': 'North Carolina',
  'Charlotte': 'North Carolina',
  'Greensboro': 'North Carolina',
  'Durham': 'North Carolina',
  'Winston-Salem': 'North Carolina',
  'Fayetteville': 'North Carolina',
  'Cary': 'North Carolina',
  'Wilmington': 'North Carolina',
  
  // Additional major cities
  'Las Vegas': 'Nevada',
  'Henderson': 'Nevada',
  'Portland': 'Oregon',
  'Phoenix': 'Arizona',
  'Tucson': 'Arizona',
  'Salt Lake City': 'Utah',
  'Philadelphia': 'Pennsylvania',
  'Pittsburgh': 'Pennsylvania',
  'Cleveland': 'Ohio',
  'Cincinnati': 'Ohio',
  'Detroit': 'Michigan',
  'Grand Rapids': 'Michigan',
  'Virginia Beach': 'Virginia',
  'Norfolk': 'Virginia',
  'Richmond': 'Virginia',
  'Baltimore': 'Maryland',
  'Minneapolis': 'Minnesota',
  'St. Paul': 'Minnesota',
  'Nashville': 'Tennessee',
  'Memphis': 'Tennessee',
  'Hartford': 'Connecticut',
  'Newark': 'New Jersey',
  'Jersey City': 'New Jersey',
  'Milwaukee': 'Wisconsin',
  'Indianapolis': 'Indiana',
  'Kansas City': 'Missouri',
  'St. Louis': 'Missouri',
  'Birmingham': 'Alabama',
  'Charleston': 'South Carolina',
  'New Orleans': 'Louisiana',
  'Louisville': 'Kentucky',
  'Oklahoma City': 'Oklahoma',
  'Tulsa': 'Oklahoma',
  
  // International cities
  'Toronto': 'Canada',
  'Montreal': 'Canada',
  'Calgary': 'Canada',
  'Ottawa': 'Canada',
  'London': 'United Kingdom',
  'Manchester': 'United Kingdom',
  'Edinburgh': 'United Kingdom',
  'Glasgow': 'United Kingdom',
  'Rome': 'Italy',
  'Milan': 'Italy',
  'Naples': 'Italy',
  'Turin': 'Italy',
  'Florence': 'Italy',
  'Berlin': 'Germany',
  'Munich': 'Germany',
  'Hamburg': 'Germany',
  'Frankfurt': 'Germany',
  'Cologne': 'Germany',
  'Paris': 'France',
  'Marseille': 'France',
  'Lyon': 'France',
  'Toulouse': 'France',
  'Nice': 'France',
  'Madrid': 'Spain',
  'Barcelona': 'Spain',
  'Valencia': 'Spain',
  'Seville': 'Spain',
  'Bilbao': 'Spain',
  'Amsterdam': 'Netherlands',
  'Rotterdam': 'Netherlands',
  'The Hague': 'Netherlands',
  'Utrecht': 'Netherlands',
  'Eindhoven': 'Netherlands',
  'Zurich': 'Switzerland',
  'Geneva': 'Switzerland',
  'Basel': 'Switzerland',
  'Bern': 'Switzerland',
  'Lausanne': 'Switzerland',
  'Stockholm': 'Sweden',
  'Gothenburg': 'Sweden',
  'Malmö': 'Sweden',
  'Uppsala': 'Sweden',
  'Oslo': 'Norway',
  'Bergen': 'Norway',
  'Trondheim': 'Norway',
  'Stavanger': 'Norway',
  'Copenhagen': 'Denmark',
  'Aarhus': 'Denmark',
  'Odense': 'Denmark',
  'Aalborg': 'Denmark',
  'Helsinki': 'Finland',
  'Espoo': 'Finland',
  'Tampere': 'Finland',
  'Turku': 'Finland',
  'Sydney': 'Australia',
  'Melbourne': 'Australia',
  'Brisbane': 'Australia',
  'Perth': 'Australia',
  'Adelaide': 'Australia',
  'Tokyo': 'Japan',
  'Osaka': 'Japan',
  'Yokohama': 'Japan',
  'Nagoya': 'Japan',
  'Kyoto': 'Japan',
  'Seoul': 'South Korea',
  'Busan': 'South Korea',
  'Incheon': 'South Korea',
  'Daegu': 'South Korea',
  'Beijing': 'China',
  'Shanghai': 'China',
  'Guangzhou': 'China',
  'Shenzhen': 'China',
  'Hangzhou': 'China',
  'Mumbai': 'India',
  'Delhi': 'India',
  'Bangalore': 'India',
  'Hyderabad': 'India',
  'Chennai': 'India',
  'São Paulo': 'Brazil',
  'Rio de Janeiro': 'Brazil',
  'Brasília': 'Brazil',
  'Salvador': 'Brazil',
  'Fortaleza': 'Brazil',
  'Mexico City': 'Mexico',
  'Guadalajara': 'Mexico',
  'Monterrey': 'Mexico',
  'Puebla': 'Mexico',
  'Tijuana': 'Mexico',
  'Tel Aviv': 'Israel',
  'Jerusalem': 'Israel',
  'Haifa': 'Israel',
  'Rishon LeZion': 'Israel',
  'Dubai': 'UAE',
  'Abu Dhabi': 'UAE',
  'Sharjah': 'UAE',
  'Cape Town': 'South Africa',
  'Johannesburg': 'South Africa',
  'Durban': 'South Africa',
  'Pretoria': 'South Africa',
  'Lagos': 'Nigeria',
  'Abuja': 'Nigeria',
  'Kano': 'Nigeria',
  'Ibadan': 'Nigeria',
  'Nairobi': 'Kenya',
  'Mombasa': 'Kenya',
  'Nakuru': 'Kenya',
  'Eldoret': 'Kenya',
  'Moscow': 'Russia',
  'St. Petersburg': 'Russia',
  'Novosibirsk': 'Russia',
  'Yekaterinburg': 'Russia',
  'Warsaw': 'Poland',
  'Kraków': 'Poland',
  'Łódź': 'Poland',
  'Wrocław': 'Poland',
  'Prague': 'Czech Republic',
  'Brno': 'Czech Republic',
  'Ostrava': 'Czech Republic',
  'Vienna': 'Austria',
  'Graz': 'Austria',
  'Linz': 'Austria',
  'Brussels': 'Belgium',
  'Antwerp': 'Belgium',
  'Ghent': 'Belgium',
  'Lisbon': 'Portugal',
  'Porto': 'Portugal',
  'Dublin': 'Ireland',
  'Cork': 'Ireland',
  'Auckland': 'New Zealand',
  'Wellington': 'New Zealand',
  'Christchurch': 'New Zealand',
  'Buenos Aires': 'Argentina',
  'Córdoba': 'Argentina',
  'Rosario': 'Argentina',
  'Santiago': 'Chile',
  'Valparaíso': 'Chile',
  'Bogotá': 'Colombia',
  'Medellín': 'Colombia',
  'Lima': 'Peru',
  'Arequipa': 'Peru',
  'Bangkok': 'Thailand',
  'Ho Chi Minh City': 'Vietnam',
  'Hanoi': 'Vietnam',
  'Jakarta': 'Indonesia',
  'Surabaya': 'Indonesia',
  'Kuala Lumpur': 'Malaysia',
  'Manila': 'Philippines',
  'Cebu': 'Philippines',
  'Istanbul': 'Turkey',
  'Ankara': 'Turkey',
  'Cairo': 'Egypt',
  'Alexandria': 'Egypt',
  'Casablanca': 'Morocco',
  'Rabat': 'Morocco',
};
