// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-deals.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-deals.ts
var DEAL_FIELDS = "id, company_name, sector, round_stage, pipeline_stage, location, website, description, round_size, post_money_valuation, revenue, total_funding_raised, deal_score, deal_lead, is_priority_deal, next_steps, last_call_date, updated_at";
var search_deals_default = defineTool({
  name: "search_deals",
  title: "Search deals",
  description: "Search the CRM deal pipeline by company name, sector, pipeline stage or round stage. Returns core deal fields.",
  inputSchema: {
    query: z.string().trim().optional().describe("Company name fragment to match."),
    sector: z.string().trim().optional().describe("Sector filter, matched loosely."),
    pipeline_stage: z.string().trim().optional().describe("Exact pipeline stage, e.g. 'Due Diligence'."),
    round_stage: z.string().trim().optional().describe("Exact round stage, e.g. 'Seed'."),
    priority_only: z.boolean().optional().describe("Only return deals flagged as priority."),
    limit: z.number().int().optional().describe("Max rows to return, default 25, max 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const limit = Math.min(Math.max(input.limit ?? 25, 1), 100);
    let q = supabaseForUser(ctx).from("deals").select(DEAL_FIELDS).order("updated_at", { ascending: false }).limit(limit);
    if (input.query) q = q.ilike("company_name", `%${input.query}%`);
    if (input.sector) q = q.ilike("sector", `%${input.sector}%`);
    if (input.pipeline_stage) q = q.eq("pipeline_stage", input.pipeline_stage);
    if (input.round_stage) q = q.eq("round_stage", input.round_stage);
    if (input.priority_only) q = q.eq("is_priority_deal", true);
    const { data, error } = await q;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, deals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-deal.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_deal_default = defineTool2({
  name: "get_deal",
  title: "Get deal detail",
  description: "Get one deal with its current investment scorecard (ARR, burn, valuation, ratings, narratives) and recent call notes. Look up by deal id or exact-ish company name.",
  inputSchema: {
    deal_id: z2.string().trim().optional().describe("Deal UUID, if known."),
    company_name: z2.string().trim().optional().describe("Company name to match when no id is given."),
    notes_limit: z2.number().int().optional().describe("How many recent call notes to include, default 5.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    if (!input.deal_id && !input.company_name) {
      throw new ToolError2("Provide either deal_id or company_name");
    }
    const supabase = supabaseForUser(ctx);
    let dealQuery = supabase.from("deals").select("*").limit(1);
    dealQuery = input.deal_id ? dealQuery.eq("id", input.deal_id) : dealQuery.ilike("company_name", `%${input.company_name}%`);
    const { data: deals, error } = await dealQuery;
    if (error) throw new ToolError2(error.message);
    const deal = deals?.[0];
    if (!deal) throw new ToolError2("No matching deal found");
    const notesLimit = Math.min(Math.max(input.notes_limit ?? 5, 1), 25);
    const [{ data: scorecard }, { data: notes }] = await Promise.all([
      supabase.from("deal_scorecards").select("*").eq("deal_id", deal.id).eq("is_current", true).maybeSingle(),
      supabase.from("call_notes").select("id, title, call_date, content").eq("deal_id", deal.id).order("call_date", { ascending: false }).limit(notesLimit)
    ]);
    const payload = { deal, scorecard: scorecard ?? null, call_notes: notes ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/add-call-note.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var add_call_note_default = defineTool3({
  name: "add_call_note",
  title: "Add call note",
  description: "Add a call note / meeting note to a deal, investor or portfolio company in the CRM. Content is markdown.",
  inputSchema: {
    title: z3.string().trim().describe("Short note title, e.g. 'Intro call with founders'."),
    content: z3.string().trim().describe("Note body in markdown."),
    call_date: z3.string().trim().optional().describe("Date of the call as YYYY-MM-DD. Defaults to today."),
    deal_id: z3.string().trim().optional().describe("Deal UUID to attach the note to."),
    investor_id: z3.string().trim().optional().describe("Investor UUID to attach the note to."),
    portfolio_company_id: z3.string().trim().optional().describe("Portfolio company UUID to attach the note to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError3("Could not resolve the signed-in user");
    if (!input.deal_id && !input.investor_id && !input.portfolio_company_id) {
      throw new ToolError3("Provide one of deal_id, investor_id or portfolio_company_id");
    }
    const { data, error } = await supabaseForUser(ctx).from("call_notes").insert({
      title: input.title,
      content: input.content,
      call_date: input.call_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      deal_id: input.deal_id ?? null,
      investor_id: input.investor_id ?? null,
      portfolio_company_id: input.portfolio_company_id ?? null,
      created_by: userId
    }).select("id, title, call_date").single();
    if (error) throw new ToolError3(error.message);
    return {
      content: [{ type: "text", text: `Created call note "${data.title}" (${data.id})` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_tasks_default = defineTool4({
  name: "list_tasks",
  title: "List tasks and reminders",
  description: "List CRM tasks/reminders visible to the signed-in user, optionally filtered to open items, a due-date window, or a specific deal.",
  inputSchema: {
    open_only: z4.boolean().optional().describe("Only return tasks that are not completed. Default true."),
    deal_id: z4.string().trim().optional().describe("Restrict to one deal UUID."),
    due_before: z4.string().trim().optional().describe("Only tasks due on or before this date (YYYY-MM-DD)."),
    due_after: z4.string().trim().optional().describe("Only tasks due on or after this date (YYYY-MM-DD)."),
    limit: z4.number().int().optional().describe("Max rows, default 25, max 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const limit = Math.min(Math.max(input.limit ?? 25, 1), 100);
    let q = supabaseForUser(ctx).from("reminders").select(
      "id, title, description, reminder_date, priority, status, task_type, is_completed, deal_id, investor_id, portfolio_company_id, assigned_to"
    ).order("reminder_date", { ascending: true }).limit(limit);
    if (input.open_only !== false) q = q.eq("is_completed", false);
    if (input.deal_id) q = q.eq("deal_id", input.deal_id);
    if (input.due_before) q = q.lte("reminder_date", input.due_before);
    if (input.due_after) q = q.gte("reminder_date", input.due_after);
    const { data, error } = await q;
    if (error) throw new ToolError4(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var create_task_default = defineTool5({
  name: "create_task",
  title: "Create task",
  description: "Create a follow-up task / reminder in the CRM, optionally linked to a deal, investor or portfolio company.",
  inputSchema: {
    title: z5.string().trim().describe("Task title."),
    reminder_date: z5.string().trim().describe("Due date as YYYY-MM-DD."),
    description: z5.string().trim().optional().describe("Optional detail for the task."),
    priority: z5.string().trim().optional().describe("Priority such as low, medium or high."),
    task_type: z5.string().trim().optional().describe("Task type label, e.g. 'Follow-up'."),
    deal_id: z5.string().trim().optional().describe("Deal UUID to link."),
    investor_id: z5.string().trim().optional().describe("Investor UUID to link."),
    portfolio_company_id: z5.string().trim().optional().describe("Portfolio company UUID to link.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError5("Could not resolve the signed-in user");
    const { data, error } = await supabaseForUser(ctx).from("reminders").insert({
      title: input.title,
      description: input.description ?? null,
      reminder_date: input.reminder_date,
      priority: input.priority ?? null,
      task_type: input.task_type ?? null,
      deal_id: input.deal_id ?? null,
      investor_id: input.investor_id ?? null,
      portfolio_company_id: input.portfolio_company_id ?? null,
      assigned_to: userId,
      created_by: userId,
      is_completed: false
    }).select("id, title, reminder_date").single();
    if (error) throw new ToolError5(error.message);
    return {
      content: [{ type: "text", text: `Created task "${data.title}" due ${data.reminder_date} (${data.id})` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/search-contacts.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var search_contacts_default = defineTool6({
  name: "search_contacts",
  title: "Search contacts",
  description: "Search CRM contacts by name, firm/company or email.",
  inputSchema: {
    query: z6.string().trim().optional().describe("Name fragment to match."),
    company: z6.string().trim().optional().describe("Company or firm fragment to match."),
    deal_id: z6.string().trim().optional().describe("Restrict to contacts linked to this deal UUID."),
    limit: z6.number().int().optional().describe("Max rows, default 25, max 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError6("Not authenticated");
    const limit = Math.min(Math.max(input.limit ?? 25, 1), 100);
    let q = supabaseForUser(ctx).from("contacts").select("id, name, title, company_or_firm, email, phone, relationship_owner, deal_id, investor_id, portfolio_company_id").order("updated_at", { ascending: false }).limit(limit);
    if (input.query) q = q.ilike("name", `%${input.query}%`);
    if (input.company) q = q.ilike("company_or_firm", `%${input.company}%`);
    if (input.deal_id) q = q.eq("deal_id", input.deal_id);
    const { data, error } = await q;
    if (error) throw new ToolError6(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-investors.ts
import { defineTool as defineTool7, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^4.4.3";
var search_investors_default = defineTool7({
  name: "search_investors",
  title: "Search investors",
  description: "Search the investor network by firm name, contact name, preferred sector or preferred investment stage.",
  inputSchema: {
    query: z7.string().trim().optional().describe("Firm name fragment to match."),
    contact_name: z7.string().trim().optional().describe("Investor contact name fragment."),
    sector: z7.string().trim().optional().describe("Preferred sector to match."),
    stage: z7.string().trim().optional().describe("Preferred investment stage, exact value."),
    limit: z7.number().int().optional().describe("Max rows, default 25, max 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError7("Not authenticated");
    const limit = Math.min(Math.max(input.limit ?? 25, 1), 100);
    let q = supabaseForUser(ctx).from("investors").select(
      "id, firm_name, contact_name, contact_email, firm_website, location, preferred_sectors, preferred_investment_stage, average_check_size, relationship_owner, last_call_date"
    ).order("updated_at", { ascending: false }).limit(limit);
    if (input.query) q = q.ilike("firm_name", `%${input.query}%`);
    if (input.contact_name) q = q.ilike("contact_name", `%${input.contact_name}%`);
    if (input.sector) q = q.contains("preferred_sectors", [input.sector]);
    if (input.stage) q = q.eq("preferred_investment_stage", input.stage);
    const { data, error } = await q;
    if (error) throw new ToolError7(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, investors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-portfolio.ts
import { defineTool as defineTool8, ToolError as ToolError8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^4.4.3";
var list_portfolio_default = defineTool8({
  name: "list_portfolio",
  title: "List portfolio companies",
  description: "List portfolio companies tracked in the CRM, optionally filtered by name or status.",
  inputSchema: {
    query: z8.string().trim().optional().describe("Company name fragment to match."),
    status: z8.string().trim().optional().describe("Exact company status value."),
    limit: z8.number().int().optional().describe("Max rows, default 25, max 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError8("Not authenticated");
    const limit = Math.min(Math.max(input.limit ?? 25, 1), 100);
    let q = supabaseForUser(ctx).from("portfolio_companies").select("id, company_name, description, status, tags, relationship_owner, updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (input.query) q = q.ilike("company_name", `%${input.query}%`);
    if (input.status) q = q.eq("status", input.status);
    const { data, error } = await q;
    if (error) throw new ToolError8(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, companies: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "arfyltduzmkrzdxjnodb";
var mcp_default = defineMcp({
  name: "dca-vc-crm",
  title: "dca-vc-crm",
  version: "0.1.0",
  instructions: [
    "Tools for the DCA VC CRM. All calls act as the signed-in CRM user and respect their access.",
    "Use `search_deals` to find deals in the pipeline, then `get_deal` for full detail including the current",
    "investment scorecard (ARR, burn, valuation, ratings, narratives) and recent call notes.",
    "Use `list_tasks` / `create_task` for follow-ups and `add_call_note` to log meeting notes.",
    "`search_contacts`, `search_investors` and `list_portfolio` cover the relationship and portfolio side."
  ].join(" "),
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_deals_default,
    get_deal_default,
    add_call_note_default,
    list_tasks_default,
    create_task_default,
    search_contacts_default,
    search_investors_default,
    list_portfolio_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
